Add Readme.md to project
Alfresco/charts pull request #6
Opened 2019-02-06 11:46 UTC by CodrinChirica

- add notes for user to state that the version in incubator is subject to change

2019-02-06 11:55 UTC, cristina-sirbu commented on README.md
> +The charts in *incubator* are subject to change as we are overriding the version with every new release.
I think I would change the order of the sentences to emphasize the warning about incubator, or some other way to get peoples attention on that.

2019-02-06 12:07 UTC, rgauss requested changes

2019-02-06 12:07 UTC, rgauss commented on README.md
> +Source repository for *Alfresco Kubernetes Charts*
This isn't actually the source, maybe:
> Helm repo for ...

2019-02-06 12:07 UTC, rgauss commented on README.md
> +Source repository for *Alfresco Kubernetes Charts*
Let's also repeat what's in the repo description in this section, except the source part 😄

2019-02-06 12:07 UTC, rgauss commented on README.md
> +The charts in *incubator* are subject to change as we are overriding the version with every new release.
Maybe "... as we may override the version with new releases."

2019-02-07 09:04 UTC, cristina-sirbu approved these changes

2019-02-07 11:30 UTC, rgauss approved these changes

2019-02-07 13:15 UTC, merged